# Generated by Django 5.1.1 on 2024-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_image_product_skin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
